# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OmdbiOSCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OmdbiOSCase
  pod 'Alamofire', '~> 5.5'
  pod 'Kingfisher', '~> 7.0'
  pod 'ProgressHUD'

  #Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging' 

end
